name: ci
run-name: "CI(${{ github.event.workflow_run.head_branch }}): ${{ github.event.workflow_run.head_commit.message }}"
on:
  pull_request:
    branches: [ main, feature/*, hotfix/* ]
  push:
    branches: [ main, feature/*, hotfix/* ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        lfs: true

    - uses: ./.github/actions/build

    - run: dotnet test -c Release -f net8.0 --no-build --collect:"XPlat Code Coverage" --consoleLoggerParameters:"Summary;Verbosity=Minimal"
      id: test-net80

    - run: dotnet test -c Release -f net6.0 --no-build --collect:"XPlat Code Coverage" --consoleLoggerParameters:"Summary;Verbosity=Minimal"
      if: matrix.os == 'ubuntu-latest'
      id: test-net60

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: logs-${{ matrix.os }}
        path: |
          msbuild.binlog
          test/**/TestResults/*.txt
          test/**/TestResults/*.trx
          test/**/TestResults/*.html
          test/**/TestResults/*.ctrf

    - name: Report failed tests
      if: ${{ failure() && (steps.test-net80.outcome == 'failure' || steps.test-net60.outcome == 'failure') }}
      uses: ./.github/actions/report-failed-tests
