name: report-test-results
run-name: "Report for ${{ github.event.workflow_run.head_branch }}: ${{ github.event.workflow_run.head_commit.message }}"
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Create Test Report
      uses: dorny/test-reporter@v1
      id : test-reports
      with:
        artifact: /^logs-(.*)/         # Name of artifact to report
        name: dotnet test              # Name of the check run which will be created
        path: 'test/TestResults/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
        fail-on-empty: true

    - name: Output message to job summary
      shell: pwsh
      run: |
        $conclusion = "${{ steps.test-reports.outputs.conclusion }}"
        $passed     = "${{ steps.test-reports.outputs.passed }}"
        $failed     = "${{ steps.test-reports.outputs.failed }}"
        $skipped    = "${{ steps.test-reports.outputs.skipped }}"
        $time       = "${{ steps.test-reports.outputs.time }}"
        $url        = "${{ steps.test-reports.outputs.url }}"
        $url_html   = "${{ steps.test-reports.outputs.url_html }}"

        $content = @"
        ## Summary of Test Report

        - **Report URL**: $url_html
 
        | Conclusion  | Passed  | Failed  | Skipped  | Time  |
        |-------------|---------|---------|----------|-------|
        | $conclusion | $passed | $failed | $skipped | $time |
        "@

        Write-Output $content >> $env:GITHUB_STEP_SUMMARY
