name: report-test-results
run-name: >
  Generate Test Report for
  ${{ github.event_name == 'pull_request' && format('PR#{0}', github.event.number) || github.event.workflow_run.head_commit.message }}
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Create Test Report
      uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
      id : test-reports
      with:
        artifact: /^logs-(.*)/         # Name of artifact to report
        name: TestReports              # Name of the `check run` which will be created
        path: 'test/TestResults/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
        fail-on-empty: true

    - name: Output message to job summary
      id: output-job-summary
      shell: pwsh
      run: |
        $conclusion = "${{ steps.test-reports.outputs.conclusion }}"
        $passed     = "${{ steps.test-reports.outputs.passed }}"
        $failed     = "${{ steps.test-reports.outputs.failed }}"
        $skipped    = "${{ steps.test-reports.outputs.skipped }}"
        $time       = "${{ steps.test-reports.outputs.time }}"
        $url        = "${{ steps.test-reports.outputs.url }}"
        $url_html   = "${{ steps.test-reports.outputs.url_html }}"

        $content = @"
        ## Summary of Test Report

        - **Report URL**: $url_html
 
        | Conclusion  | Passed  | Failed  | Skipped  | Time  |
        |-------------|---------|---------|----------|-------|
        | $conclusion | $passed | $failed | $skipped | $time |
        "@

        Write-Output $content >> $env:GITHUB_STEP_SUMMARY

        # Write content to outputs
        'report<<$EOF' >> $env:GITHUB_OUTPUT
        $content       >> $env:GITHUB_OUTPUT
        '$EOF'         >> $env:GITHUB_OUTPUT


    - name: Update PullRequest comment
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      with:
        message: ${{ steps.output-job-summary.outputs.report }}

